apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:  
  name: webgatos
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:  
  rules:
   - http:
      paths:
      - path: /webgatos
        pathType: Prefix
        backend:
          service:
            name: webgatos
            port:
              number: 5000